# Generated by Django 4.1.2 on 2022-10-18 09:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0004_orderproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='address',
            field=models.CharField(default=datetime.datetime(2022, 10, 18, 9, 24, 44, 40394, tzinfo=datetime.timezone.utc), max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 10, 18, 9, 25, 12, 38544, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='name',
            field=models.CharField(default=datetime.datetime(2022, 10, 18, 9, 25, 47, 308166, tzinfo=datetime.timezone.utc), max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='phone_number',
            field=models.CharField(default='Kanat', max_length=50),
            preserve_default=False,
        ),
    ]
